name: 'Test PHP'
description: 'Testing PHP projects - lint, style, compatiblity, unit tests'

inputs:
  php-versions:
    description: 'Project PHP versions to test'
    required: true
    default: '["5.5", "5.6", "7.0"]'
  minimum-php-compatible-version:
    description: 'Minimum PHP version to test compatibility with'
    required: true
    default: '5.5'
  lint-php-versions:
    description: 'List of PHP versions to run lint on'

#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - run: echo "Action in workflows"
      shell: bash
#      with:
#        php-versions: ${{ inputs.php-versions }}
#    - run: echo Hello ${{ inputs.who-to-greet }}.
#      shell: bash
#    - id: random-number-generator
#      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
#      shell: bash
#    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#      shell: bash
#    - run: goodbye.sh
#      shell: bash
