name: Run PHPCompatibility checks

on:
  workflow_call:

jobs:
  php-compatibility-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.5-']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard against no PHP changes
        id: guard
        run: |
          if [[ -z $(git diff --name-only --diff-filter=d origin/main...HEAD | grep '\.php$') ]]; then
            echo "HAS_CHANGES=false" >> "$GITHUB_OUTPUT"
          else
            echo "HAS_CHANGES=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup PHP
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          extensions: tokenizer, xmlwriter, SimpleXML
          ini-values: max_execution_time=0, memory_limit=-1
          coverage: none
          tools: cs2pr, phpcs, phpcompatibility/php-compatibility
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure PHP CodeSniffer - setup PHPCompatibility rules
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        run: |
          phpcs \
            --config-set installed_paths ${HOME}/.composer/vendor/phpcompatibility/php-compatibility/PHPCompatibility \
            -i

      - name: Run Stylecheck with PHP CodeSniffer
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        run: |
          git diff --name-only --diff-filter=d origin/main...HEAD > filelist.txt
          ls -al filelist.txt
          phpcs \
              -q \
              --file-list=filelist.txt \
              --extensions=php \
              --report=checkstyle \
              --standard=PHPCompatibility \
              --runtime-set testVersion ${{ matrix.php-versions }} | cs2pr
