name: Run Stylecheck

on:
  workflow_call:

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard against no PHP changes
        id: guard
        run: |
          if [[ -z $(git diff --name-only --diff-filter=d origin/main...HEAD | grep '\.php$') ]]; then
            echo "HAS_CHANGES=false" >> "$GITHUB_OUTPUT"
          else
            echo "HAS_CHANGES=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup PHP
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          extensions: tokenizer, xmlwriter, SimpleXML
          ini-values: max_execution_time=0, memory_limit=-1
          coverage: none
          tools: cs2pr, phpcs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure PHP CodeSniffer - set default standard to PSR12
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        run: phpcs --config-set default_standard PSR12

      - name: Run Stylecheck with PHP CodeSniffer
        if: ${{ steps.guard.outputs.HAS_CHANGES == 'true' }}
        run: |
          git diff --name-only --diff-filter=d origin/main...HEAD > filelist.txt
          ls -al filelist.txt
          phpcs \
              -q \
              --file-list=filelist.txt \
              --extensions=php \
              --report=checkstyle | cs2pr
